# Generated by Django 3.1.4 on 2020-12-06 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0003_auto_20201207_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testmodel',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Custom Test Model'},
        ),
        migrations.CreateModel(
            name='ModelX',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Test_content', to='DRF.testmodel')),
            ],
            options={
                'verbose_name_plural': 'Model X',
                'ordering': ('-created_at',),
            },
        ),
    ]
