# Generated by Django 3.1.4 on 2020-12-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DRF', '0004_auto_20201207_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelx',
            name='test_content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_content', to='DRF.testmodel'),
        ),
    ]
